# URL koneksi (tanpa username dan password)
spring.datasource.url=jdbc:postgresql://ep-divine-mountain-aop6oxum-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# Username dan Password dipisah di sini
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ohOMG7H9AFBm

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true